// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFvn7lWkS0Xe1tG2NBUhiuNQfeiAd3VT8',
    appId: '1:373731403649:web:5ec5e921ffc31450b62a80',
    messagingSenderId: '373731403649',
    projectId: 'videoestimate-41322',
    authDomain: 'videoestimate-41322.firebaseapp.com',
    storageBucket: 'videoestimate-41322.firebasestorage.app',
    measurementId: 'G-0GXEQDFHEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbk7KT0r7b4in89IOcgUVT03Gav-Ontig',
    appId: '1:373731403649:android:ec0571c86c6e432db62a80',
    messagingSenderId: '373731403649',
    projectId: 'videoestimate-41322',
    storageBucket: 'videoestimate-41322.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyLPBLVjzddDOjTT8cwl1PS9NmpF7IyEU',
    appId: '1:373731403649:ios:19cdc5618fc38f50b62a80',
    messagingSenderId: '373731403649',
    projectId: 'videoestimate-41322',
    storageBucket: 'videoestimate-41322.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
